package CAS;

/**
 * Created by jack on 1/13/2017.
 */
public enum IdentificationType {
    INTEGER,
    CONSTANT,
    NEGATIVE_CONSTANT,
    FRACTION_STANDARD_FORM,
    EXPLICIT_ALGEBRAIC_NUMBER,
    RATIONAL_NUMBER_EXPRESSION,
    AUTOSIMPLIFIED_EXPRESSION;
}
